apiVersion: v1
kind: Service
metadata:
  name: go-server
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: go-server
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews-route
spec:
  hosts:
  - go-server.default.svc.cluster.local
  http:
  - name: go-server
    route:
    - destination:
        host: go-server.default.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: go-server
spec:
  host: go-server.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true
